apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
        - name: web-nginx
          image: theidiothuy45/web-thingy:v1
          ports:
          - containerPort: 80
